### ISSUE TITLE
Integration with pears

### ISSUE THREAD

**Issue by gegoune** [codybuell/compe-lbdb#1]
Hi there, great thanks for that, was missing it ever since ditching coc!

I have run into an issue with my custom enter confirmation for selected item. I use pears and have such configuration:

```lua
require('pears').setup(function(conf)
  conf.on_enter(function(pears_on_enter)
    if vim.fn.pumvisible() == 1 and vim.fn.complete_info().selected ~= -1 then
      return vim.fn['compe#confirm'] '<CR>'
    else
      pears_on_enter()
    end
  end)

  conf.pair('<', nil)
end)
```

On top of that `completeopts` is
```lua
vim.opt.completeopt = { 'menuone', 'noselect', 'noinsert' }
```

Trying to confirm with enter deletes from cursor position till the end of the buffer, only inserts two characters from completion and repeats last entered character.

Confirming with `<C-y>` works correctly.

Apologies for cryptic description, but unfortunately given sensitive nature of completions offered by your plugin I can't provide you with screen recording.

**Comment by codybuell** [comment]
@gegoune Are you running into similar behavior with any of your other completion sources? I'm unfamiliar with pears and at first glance it sounds like an issue with how it interacts with nvim-compe rather than the completion source.

**Comment by gegoune** [comment]
Hey @codybuell , I only use compe-tmux as another external source, all other sources are shipped with compe and I have no such problem with any of those.

**Comment by codybuell** [comment]
@gegoune if you can provide a minimal configuration that replicates the issue I'll take a look.

**Comment by gegoune** [comment]
I have just tried to create one and it seems to be confirming fine, then I checked against my main configuration again and it also works fine. Very interesting.

But what I have noticed now is that presented completions are either `name` or `email address`, but never `'name' <email address>` as returned by `lbdbq`. Also there is different number of returned results from `lbdbq <some name>` and in nvim when typing `<some name>`.

**Comment by codybuell** [comment]
The `'name' <email>` completion will only occur if it detects that you are in an email header, meaning the current line starts with `To:`, `From:`, `Cc:`, etc. If you feel that it's needed in other locations we could put in an option to make it global. As far as result counts, the script is doing deduplication based on lowercased versions of email addresses. UserName@host.com and username@host.com will present as two records from `lbdbq` but one in the completion source.

**Comment by gegoune** [comment]
Ah, I see, in which case I am able to reproduce the issue on `To:` line with

```lua
vim.opt.termguicolors = true
local install_path = '/tmp/nvim/site/pack/packer/start/packer.nvim'

vim.opt.packpath = '/tmp/nvim/site'
vim.opt.runtimepath = install_path
vim.opt.runtimepath:append '/usr/local/Cellar/neovim/HEAD-33b4513/share/nvim/runtime'

local function load_plugins()
  require('packer').startup {
    function(use)
      use 'wbthomason/packer.nvim'
      use { 'hrsh7th/nvim-compe', requires = { { 'codybuell/compe-lbdb' } } }
      use { 'steelsojka/pears.nvim' }
    end,
    config = { package_root = '/tmp/nvim/site/pack' },
  }
end

_G.load_config = function()
  require('pears').setup(function(conf)
    conf.on_enter(function(pears_on_enter)
      if vim.fn.pumvisible() == 1 and vim.fn.complete_info().selected ~= -1 then
        return vim.fn['compe#confirm'] '<CR>'
      else
        pears_on_enter()
      end
    end)

    conf.pair('<', nil)
  end)

  require('compe').setup {
    preselect = 'always',
    source = {
      lbdb = true,
    },
  }
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd 'autocmd User PackerComplete ++once lua load_config()'
else
  load_plugins()
  _G.load_config()
end
```

**Comment by codybuell** [comment]
Thanks for providing that. It looks like pears is trying to do something with the single quotes around the name when passing in the completion. If I remove the single quote from what compe-lbdb provides it works as expected. Unfortunately the single quotes are needed to ensure addresses are parsed correctly by mail clients in case the recipients name contains odd characters like parenthesis around a title.

I'm not familiar with pears, but it should be possible to write a rule / config to have it ignore single quotes when in a mail filetype header. This is how compe-lbdb detects if you are in the header: https://github.com/codybuell/compe-lbdb/blob/master/lua/compe_lbdb/utils.lua#L92-L100

**Comment by gegoune** [comment]
@codybuell Thanks for looking into this, your explanation makes sense. @steelsojka maybe you have any idea what could be done here? I would like to keep single quotes pairing in mail as well.

**Comment by codybuell** [comment]
Closing this out, should be handled by a pears configuration or patch.
