### ISSUE TITLE
Extension for nvim-cmp

### ISSUE THREAD

**Issue by gegoune** [codybuell/compe-lbdb#2]
I am not sure if you are aware on work in progress successor for nvim-compe, https://github.com/hrsh7th/nvim-cmp. Do you think you will be willing to support that plugin as well?

**Comment by codybuell** [comment]
Was not aware of if nvim-cmp yet. Will likely be able to spend some time with it and port over this plugin over the coming holidays. Will post updates here if I'm able to get to it.

**Comment by gegoune** [comment]
That's very nice of you, thanks! compe is basically obsolete now, cmp is a replacement.

**Comment by codybuell** [comment]
@gegoune give this a go:
https://github.com/codybuell/cmp-lbdb
